theme: jekyll-theme-cayman
title: Interdisciplinary Workshop on Trust, Identity, Privacy, and Security in the Digital Economy (DETIPS 2020)
description: in affiliation with ESORICS 2020 (Virtual event)
